// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmdT7cHK51_18FCYOK7diVnP98GPUTN0',
    appId: '1:118953206524:web:c671b9de1d1325f5b0ad79',
    messagingSenderId: '118953206524',
    projectId: 'devshepherd-5d186',
    authDomain: 'devshepherd-5d186.firebaseapp.com',
    storageBucket: 'devshepherd-5d186.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlShNWf5w23f74nFvPjPDj3YdwXMfFsnw',
    appId: '1:118953206524:android:a80ac2066eb5a8a0b0ad79',
    messagingSenderId: '118953206524',
    projectId: 'devshepherd-5d186',
    storageBucket: 'devshepherd-5d186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmA_TmQRPSQ6w__d20ApOSme8p6kdQ7MY',
    appId: '1:118953206524:ios:6c1fd2411281ed04b0ad79',
    messagingSenderId: '118953206524',
    projectId: 'devshepherd-5d186',
    storageBucket: 'devshepherd-5d186.firebasestorage.app',
    iosBundleId: 'com.example.devShepherd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmA_TmQRPSQ6w__d20ApOSme8p6kdQ7MY',
    appId: '1:118953206524:ios:6c1fd2411281ed04b0ad79',
    messagingSenderId: '118953206524',
    projectId: 'devshepherd-5d186',
    storageBucket: 'devshepherd-5d186.firebasestorage.app',
    iosBundleId: 'com.example.devShepherd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmdT7cHK51_18FCYOK7diVnP98GPUTN0',
    appId: '1:118953206524:web:bf41a83f1a1ce494b0ad79',
    messagingSenderId: '118953206524',
    projectId: 'devshepherd-5d186',
    authDomain: 'devshepherd-5d186.firebaseapp.com',
    storageBucket: 'devshepherd-5d186.firebasestorage.app',
  );
}
